// Generated by CoffeeScript 1.8.0
(function() {
  var superagent;

  superagent = require('superagent');

  module.exports = function(method, uri, data, callback) {
    var sa, url;
    url = "" + config.HOST + uri;
    if (typeof data === 'function') {
      callback = data;
      data = null;
    }
    sa = superagent[method](url);
    sa.set('User-Agent', 'SuperAgent');
    sa.set('X-Requested-With', 'XMLHttpRequest');
    sa.set('Authorization', "OAuth2 " + token);
    if (data) {
      sa.send(data);
    }
    return sa.end(callback);
  };

}).call(this);
