// Generated by CoffeeScript 1.8.0
(function() {
  var Yiban, superagent;

  superagent = require('superagent');

  Yiban = (function() {
    function Yiban() {}

    Yiban.prototype.name = 'yiban';

    Yiban.prototype.host = 'https://openapi.yiban.cn';

    Yiban.prototype.client_id = 'set_client_id';

    Yiban.prototype.client_secret = 'set_client_secret';

    Yiban.prototype.authorize_uri = "/oauth/authorize";

    Yiban.prototype.access_token_uri = "/oauth/access_token";

    Yiban.prototype.redirect_uri = "http://example.com/yiban/callback";

    Yiban.prototype.constrcutor = function(client_id, client_secret, redirect_uri) {
      this.client_id = client_id;
      this.client_secret = client_secret;
      return this.redirect_uri = redirect_uri;
    };

    Yiban.prototype._request = function(method, uri, data, callback) {
      var sa, url;
      url = "" + this.host + uri;
      if (typeof data === 'function') {
        callback = data;
        data = null;
      }
      sa = superagent[method](url);
      sa.set('User-Agent', 'Teambition Yiban/1');
      sa.set('X-Requested-With', 'XMLHttpRequest');
      if (data) {
        sa.send(data);
      }
      return sa.end(callback);
    };

    Yiban.prototype.getAccessToken = function(code, callback) {
      return this._request('post', this.access_token_uri, {
        client_id: this.client_secret,
        client_secret: this.client_secret,
        code: code,
        redirect_uri: this.redirect_uri
      }, function(err, res) {
        return callback(err, res.body);
      });
    };

    Yiban.prototype.getAuthorizeUrl = function() {
      var authorizeUrl, key, qs, val;
      qs = {
        client_id: this.client_id,
        redirect_uri: encodeURIComponent(this.redirect_uri),
        display: 'web'
      };
      authorizeUrl = "" + this.host + this.authorize_uri + "?";
      for (key in qs) {
        val = qs[key];
        authorizeUrl += "" + key + "=" + val + "&";
      }
      return authorizeUrl;
    };

    return Yiban;

  })();

  module.exports = new Yiban;

}).call(this);
